name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint TypeScript code
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Synthesize CloudFormation template
      run: npx cdk synth
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Python dependencies
      run: |
        cd app
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Run Python tests
      run: |
        cd app
        python -m pytest tests/ --cov=src
        
  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Run dependency vulnerability check
      run: npm audit --production
      continue-on-error: true
      
    - name: Run CFN Nag scan
      uses: stelligent/cfn_nag@master
      with:
        input_path: cdk.out
        extra_args: --fail-on-warnings